### ISSUE TITLE
Is Jepsen can use to fuzz Kubernetes itself.

### ISSUE THREAD

**Issue by Sivakajan-tech** [gridgain/jepsen#9]
Hi, I apologize for raising this question on GitHub. I'd like to inquire about using Jepsen or Mallory to fuzz the Kubernetes application (https://github.com/kubernetes/kubernetes). We're developing a fuzzer for Kubernetes and require a comparison matrix to assess its effectiveness.

As far as I'm aware, Jepsen and Mallory are prominent fuzzers for distributed systems. However, the Jepsen fuzzer's [README.md](https://github.com/gridgain/jepsen#docker-unsupported) file indicates that Docker is not supported. Can you give me an insight that we can use Jepsen or Mallory to fuzz the Kubernetes? 

Anyone from the contributed please add your thoughts!!!

**Comment by ahitrin** [comment]
@Sivakajan-tech could you please address your question to the upstream Jepsen project? 
https://github.com/jepsen-io/jepsen

**Comment by Sivakajan-tech** [comment]
Thanks @ahitrin .

**Comment by Sivakajan-tech** [comment]
BTW, @ahitrin in this repository, only you said that Jepson can not be used to calculate the clock skew, this is happening in the container orchestration platforms. [README.md](https://github.com/gridgain/jepsen#docker-unsupported)

**Comment by ahitrin** [comment]
This comment was from original author: https://github.com/gridgain/jepsen/blame/main/README.md#L96
I didn't work with clock skew in Jepsen. Sorry but I'm afraid I can't help you with it.

**Comment by Sivakajan-tech** [comment]
I follow up here [jepsen-io/jepsen#586](https://github.com/jepsen-io/jepsen/issues/586)
